### ISSUE TITLE
Markup currently doesn't support single quotes

### ISSUE THREAD

**Issue by DoctorsHacking** [thestd/language-rockstar#1]
Firstly a big thanks! Without the highlighter it would have been awful hours of coding.
The only error I encountered was when using single quotes; everything after it until closed again will be colored yellow. Maybe just ignore them?

**Comment by faradzhev** [comment]
Thanks for using it and sharing your feedback!
I'll check that bug shortly.
As I remember, Rockstar didn't have single quotes in the documentation. Did it?

**Comment by faradzhev** [comment]
I've disabled single quotes for now.
And added support for single quote (e.g., in `He's a bastard` Atom will highlight `'s` the same as `is`).
